// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Week_8_Authentication.Models;

public partial class Publisher
{
    public int PublisherId { get; set; }

    public string PublisherName { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}